# Generated by Django 3.2.6 on 2021-08-22 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlimages', '0002_remove_lead_image_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='image_id',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
